;==========================================================
;
;
;   ██████╗  ██████╗ ██╗  ██╗   ██╗██████╗  █████╗ ██████╗
;   ██╔══██╗██╔═══██╗██║  ╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗
;   ██████╔╝██║   ██║██║   ╚████╔╝ ██████╔╝███████║██████╔╝
;   ██╔═══╝ ██║   ██║██║    ╚██╔╝  ██╔══██╗██╔══██║██╔══██╗
;   ██║     ╚██████╔╝███████╗██║   ██████╔╝██║  ██║██║  ██║
;   ╚═╝      ╚═════╝ ╚══════╝╚═╝   ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝
;
;
;   To learn more about how to configure Polybar
;   go to https://github.com/polybar/polybar
;
;   The README contains a lot of information
;
;==========================================================

[colors]
background = #0f0e08
background-alt = #272442
foreground = #a17bd4
primary = #624982
secondary = #8ABEB7
alert = #A54242
disabled = #261836

[bar/example]
width = 100%
height = 24pt
radius = 0

; dpi = 96

background = ${colors.background}
#background-1 = "#102227"
foreground = ${colors.foreground}

line-size = 3pt

border-size = 0pt
border-color = #00000000

padding-left = 0
padding-right = 1

module-margin = 1

separator = |
separator-foreground = ${colors.disabled}

font-0 = JetBrains Mono:bold;2
font-1 = Font Awesome 7 Free :style=Regular;2
font-2 = Font Awesome 7 Brands :style=Regular
font-3 = Font Awesome 7 Free Solid:style=Solid;2
font-4 = Twitter Color Emoji:style=Regular 

modules-left = xworkspaces xwindow
modules-right = pulseaudio memory cpu battery alsa xkeyboard date tray

cursor-click = pointer
cursor-scroll = ns-resize

enable-ipc = true

; tray-position = right

; wm-restack = generic
; wm-restack = bspwm
; wm-restack = i3

; override-redirect = true

[module/text]
type = custom/text
format = <content>
content = "    "
content-background = ${colors.foreground}
content-foreground = ${colors.background}
;format-padding = 4

[module/xworkspaces]
type = internal/xworkspaces

label-active = %icon% 
label-active-background = ${colors.background-alt}
label-active-underline= ${colors.primary}
label-active-padding = 1

label-occupied = %icon%
label-occupied-padding = 1

label-urgent = %icon%
label-urgent-background = ${colors.alert}
label-urgent-padding = 1

label-empty = %icon%
label-empty-foreground = ${colors.disabled}
label-empty-padding = 1

icon-0 = 1;
icon-1 = 2;
icon-2 = 3;
icon-3 = 4;
icon-4 = 5;
icon-5 = 6;
icon-6 = 7;
icon-7 = 8;
icon-8 = 9;

[module/xwindow]
type = internal/xwindow
label = %title:0:60:...%

[module/filesystem]
type = internal/fs
interval = 25

mount-0 = /

label-mounted = %{F#b43003}%mountpoint%%{F-} %percentage_used%%

label-unmounted = %mountpoint% not mounted
label-unmounted-foreground = ${colors.disabled}

[module/pulseaudio]
type = internal/pulseaudio
sink = alsa_output.usb-HP__Inc_HyperX_Cloud_II_Core_Wireless-00.analog-stereo

format-volume-prefix = "VOL "
format-volume-prefix-foreground = ${colors.primary}
format-volume = <label-volume>

label-volume = %percentage%%

label-muted = muted
label-muted-foreground = ${colors.disabled}

[module/xkeyboard]
type = internal/xkeyboard
blacklist-0 = num lock
blacklist-1 = caps lock

format = <label-layout>
label-layout = %icon%
label-layout-foreground = ${colors.foreground}

layout-icon-0 = us;US
layout-icon-1 = ru;RU

[module/memory]
type = internal/memory
interval = 5
format-prefix = " "
format-prefix-foreground = ${colors.primary}
label = %used:0.1f% GB

[module/cpu]
type = internal/cpu
interval = 5
format-prefix = " "
format-prefix-foreground = ${colors.primary}
label = %percentage%%

[module/battery]
type = internal/battery
full-at = 99
low-at = 5
battery = BAT1
adapter = ADP1
poll-interval = 5

format-charging = ↑ <ramp-capacity> <label-charging>
format-discharging = ↓ <ramp-capacity> <label-discharging>
label-charging = %percentage%%
label-discharging = %percentage%%
label-full = 
label-full-foreground = ${colors.primary}
label-low = BATTERY LOW

ramp-capacity-0 = 
ramp-capacity-1 = 
ramp-capacity-2 = 
ramp-capacity-3 = 
ramp-capacity-4 = 
ramp-capacity-foreground = ${colors.primary}

animation-charging-0 = 
animation-charging-1 = 
animation-charging-2 = 
animation-charging-3 = 
animation-charging-4 = 
animation-charging-framerate = 750

animation-discharging-0 = 
animation-discharging-1 = 
animation-discharging-2 = 
animation-discharging-3 = 
animation-discharging-4 = 
animation-discharging-framerate = 500

animation-low-0 = !
animation-low-1 = 
animation-low-framerate = 200

[module/backlight]
type = internal/backlight

; XRandR output to get get values from
; Default: the monitor defined for the running bar
use-actual-brightness = true
card = amdgpu_bl0
poll-interval = 0
enable-scroll = true
scroll-interval = 10

; Create scroll handlers used to set the backlight value
; Default: true
format = <label> <bar>

; Available tokens:
;   %percentage% (default)
label = 
label-foreground = ${colors.primary}

; Only applies if <ramp> is used
;ramp-0 = 🌕
;ramp-1 = 🌔
;ramp-2 = 🌓
;ramp-3 = 🌒
;ramp-4 = 🌑

; Only applies if <bar> is used
bar-width = 11
bar-indicator = 
bar-fill = ❱
bar-empty = ❱
bar-empty-foreground = ${colors.disabled} 
bar-gradient = true
bar-foreground-0 = #00ff00
bar-foreground-1 = #ff9900
bar-foreground-2 = #ff0000

[module/alsa]
type = internal/pulseaudio
sink = alsa_output.usb-HP__Inc_HyperX_Cloud_II_Core_Wireless-00.analog-stereo
format-volume = <ramp-volume> <bar-volume>
label-muted = 
label-muted-foreground = #66
ramp-volume-0 = 
ramp-volume-1 = 
ramp-volume-2 = 
ramp-headphones-0 = 
ramp-headphones-1 = 
ramp-volume-foreground = ${colors.primary}

bar-volume-width = 11
bar-volume-indicator = 
bar-volume-fill = ❱
bar-volume-empty = ❱
bar-volume-empty-foreground = ${colors.disabled} 
bar-volume-gradient = true
bar-volume-foreground-0 = #00ff00
bar-volume-foreground-1 = #ff9900
bar-volume-foreground-2 = #ff0000

#[network-base]
#type = internal/network
#interval = 5
#format-connected = <label-connected>
#format-disconnected = <label-disconnected>
#label-disconnected = %{F#F0C674}%ifname%%{F#707880} disconnected

#[module/wlan]
#inherit = network-base
#interface-type = wireless
#label-connected = %{F#F0C674}%ifname%%{F-} %essid% %local_ip%

#[module/eth]
#inherit = network-base
#interface-type = wired
#label-connected = %{F#F0C674}%ifname%%{F-} %local_ip%
[module/tray]
type = internal/tray

format-margin = 8px
tray-spacing = 8px

[module/date]
type = internal/date
interval = 1

#date = %H:%M
date = %d.%m %H:%M:%S

format-prefix = " "
format-prefix-foreground = ${colors.primary}
label = %date%
;label-foreground = ${colors.primary}

;[module/tray]
;type = internal/tray
;format = <tray>
;format-margin = 8px
;tray-spacing = 8px

[settings]
screenchange-reload = true
pseudo-transparency = true

; vim:ft=dosini
